#!/usr/bin/with-contenv bash

# `flexget daemon` runs all tasks in the config every hour by default, for more
# options see https://flexget.com/Plugins/Daemon/scheduler.
#
# `--autoreload-config` reloads the config *before* running the tasks, not
# when the configuration actually changes.
#

if [ -f /config/.config-lock ]; then
    rm /config/.config-lock
fi

s6-setuidgid abc /usr/bin/flexget \
    --loglevel "${FLEXGET_LOG_LEVEL:-debug}" \
    daemon start --autoreload-config
