#!/usr/bin/with-contenv bash

pip install -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951
pip install -U setuptools>=36
pip install -U flexget
