#!/usr/bin/with-contenv bash

if [[ "$TORRENT_PLUGIN" == *"deluge"* ]]; then
    apk add --update --no-cache --virtual=build-dependencies \
        apk-tools

    apk add --no-cache \
        py-attrs@edge

    apk add --no-cache \
        deluge@testing

    # Deluge is missing dependencies.
    # https://bugs.alpinelinux.org/issues/7154

    apk add --no-cache --virtual=build-dependencies \
        g++ \
        gcc \
        libffi-dev \
        python2-dev

    pip2 install -U \
        constantly \
        incremental \
        service_identity
fi
